name: 'Synopsys Unified'
description: 'Scan using synopsys tools'
author: 'Synopsys Inc'
inputs:
  coverity_url:
    description: 'Coverity url'
    required: true
  coverity_user:
    description: 'Coverity user name'
    required: true
  coverity_pasphrase:
    description: 'Coverity password'
    required: true
  coverity_project_name:
    description: 'Coverity Project Name'
    required: true
  coverity_stream_name:
    description: 'Coverity Stream Name'
    required: true
  coverity_install_directory:
    description: 'Coverity Install Directory'
    required: false
  coverity_policy_view:
    description: 'Coverity Policy View'
    required: false
  coverity_repository_name:
    description: 'Repository Name'
    required: false
  coverity_branch_name:
    description: 'Branch name'
    required: false
  polaris_accessToken:
    description: 'Polaris Access Token'
    required: false
  polaris_application_name:
    description: 'Polaris Application Name'
    required: false
  polaris_project_name:
    description: 'Polaris Project Name'
    required: false
  polaris_assessment_types:
    description: 'Polaris Assess Types SAST/SCA'
    required: false
  polaris_serverUrl:
    description: 'Polaris Server URL'
    required: false
  synopsys_bridge_path:
    description: 'Synopsys bridge path'
    required: false
  bridge_download_url:
    description: 'URL to download bridge from'
    required: false
  blackduck_url:
    description: 'URL for blackduck hub'
    required: false
  blackduck_apiToken:
    description: 'API token to access blackduck'
    required: false
  blackduck_install_directory:
    description: 'Directory to find or install detect'
    required: false
  blackduck_scan_full:
    description: 'Scan Mode. (true for intelligent scan & false for rapid scan)'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
