name: 'Synopsys Action'
branding:
  icon: 'shield'
  color: 'purple'
description: 'Find and fix software weaknesses and vulnerabilities during development, before you ship or deploy!'
author: 'Synopsys Inc'
inputs:
  coverity_url:
    description: 'Coverity url'
    required: false
  coverity_user:
    description: 'Coverity user name'
    required: false
  coverity_passphrase:
    description: 'Coverity password'
    required: false
  coverity_project_name:
    description: 'Coverity Project Name'
    required: false
  coverity_stream_name:
    description: 'Coverity Stream Name'
    required: false
  coverity_install_directory:
    description: 'Coverity Install Directory'
    required: false
  coverity_policy_view:
    description: 'Coverity Policy View'
    required: false
  coverity_repository_name:
    description: 'Repository Name'
    required: false
  coverity_branch_name:
    description: 'Branch name'
    required: false
  coverity_local:
    description: 'Flag to enable/disable to run coverity scan locally.'
    required: false
  polaris_accessToken:
    description: 'Polaris Access Token'
    required: false
  polaris_application_name:
    description: 'Polaris Application Name'
    required: false
  polaris_project_name:
    description: 'Polaris Project Name'
    required: false
  polaris_assessment_types:
    description: 'Polaris Assess Types SAST/SCA'
    required: false
  polaris_serverUrl:
    description: 'Polaris Server URL'
    required: false
  synopsys_bridge_install_directory:
    description: 'Synopsys Bridge Install Directory'
    required: false
  bridge_download_url:
    description: 'URL to download bridge from'
    required: false
  blackduck_url:
    description: 'URL for blackduck hub'
    required: false
  blackduck_apiToken:
    description: 'API token to access blackduck'
    required: false
  blackduck_install_directory:
    description: 'Directory to find or install detect'
    required: false
  blackduck_scan_full:
    description: 'Scan Mode. (true for intelligent scan & false for rapid scan)'
    required: false
  blackduck_scan_failure_severities:
    description: 'If provided, Blackduck will break the build if any issues produced match one of the given severities'
    required: false
  blackduck_automation_fixpr:
    description: 'If set as true, separate Fix PRs will be created if vulnerability is found after scan'
    required: false
  bridge_blackduck_fixpr_enabled:
    description: 'If set as true, separate Fix PRs will be created if vulnerability is found after scan'
    required: false
  bridge_blackduck_fixpr_maxCount:
    description: 'If set as true, Fix PRs will be created if vulnerability is found after scan'
    required: false
  bridge_blackduck_fixpr_createSinglePR:
    description: 'If set as true, single Fix PR will be created for all vulnerabilities found after scan'
    required: false
  bridge_blackduck_fixpr_filter_by:
    description: 'Filter criteria for Fix PR'
    required: false
  bridge_blackduck_fixpr_filter_severities:
    description: 'If provided, Fix PRs will be created only for given severities'
    required: false
  bridge_blackduck_fixpr_useLongTermUpgradeGuidance:
    description: 'Flag to enable long term upgrade guidance'
    required: false
  bridge_download_version:
    description: 'If provided, Synopsys-action will configure the version of Bridge'
    required: false
  blackduck_automation_prcomment:
    description: 'If provided, PR will be raised for each issue from blackduck results'
    required: false
  coverity_automation_prcomment:
    description: 'If provided, PR will be raised for each issue from coverity results'
    required: false
  github_token:
    description: 'Github token to be used for git related rest operation'
    required: false
  include_diagnostics:
    description: 'To include diagnostics info and export as zip'
    required: false
  diagnostics_retention_days:
    description: 'Number of days to keep the diagnostics files downloadable'
    required: false
  bridge_network_airgap:
    description: 'If provided, Synopsys Action will be using local network to download and execute bridge .'
    required: false
  bridge_coverity_version:
    description: 'If provided, Synopsys Action will download specific version of coverity thin client to use.'
    required: false  
runs:
  using: 'node16'
  main: 'dist/index.js'
