name: "E2E Deployment testing workflow for Windows"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
     runs-on: [ E2E-test-linux ]
     steps:
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -qqy awscli jq openjdk-11-jdk
      - name: unit testing
        run: |
          echo "unit testing stage"
      - name: build
        run: |
          echo "build stage"
      - name: pop
        run: |
          echo "Pop stage"
      - name: e2e
        run: |
          aws s3 cp --recursive s3://e2e-integrations-test/e2e-artifacts/integrations integrations --no-progress
          ls -al
          aws s3 cp s3://e2e-integrations-test/e2e-artifacts/test-integrations-0.0.1-SNAPSHOT.jar test-integrations-0.0.1-SNAPSHOT.jar --no-progress
          ls -al
          if [[ $GITHUB_EVENT_NAME == 'push' ]]; then
            echo github.action.version=${GITHUB_REF#refs/heads/} >> /tmp/test.properties
          else
            echo github.action.version=$GITHUB_HEAD_REF >> /tmp/test.properties
          fi
          echo "product=integrations" >> /tmp/test.properties
          echo "product.name=integrations" >> /tmp/test.properties
          echo "scm=github" >> /tmp/test.properties
          echo "runner=Windows" >> /tmp/test.properties
          echo "runner.os=Windows" >> /tmp/test.properties
          echo "pipeline=true" >> /tmp/test.properties
          echo "cloud.storage=S3" >> /tmp/test.properties
          chmod 755 test-integrations-0.0.1-SNAPSHOT.jar
          pwd  && ls -la
          cat /tmp/test.properties
          java -enableassertions -DPropertyManager.file=/tmp/test.properties -jar test-integrations-0.0.1-SNAPSHOT.jar -testjar test-integrations-0.0.1-SNAPSHOT.jar  -xmlpathinjar com/synopsys/test/integrations/cases/suites/deployment/testng-github-scm.xml
      
      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: test-output
      - name: publish
        run: |
          echo "publish stage"
